id: IA6C16453
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:41:44.530791+00:00
last_modified: 2022-12-14 10:41:44.530796+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-010
  eft-text-version: 1.1.9 2021
  title: Toh_151-The_Questions_of_Pratibhanamati-v2
bases:
  3A55:
    source_metadata: null
    order: 1
    base_file: 3A55.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
